kind: Deployment
apiVersion: apps/v1
metadata:
  name: tenant-quota-exporter
  namespace: paas-monitoring
  labels:
    app: tenant-quota-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-quota-exporter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tenant-quota-exporter
    spec:
      containers:
        - resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          name: tenant-quota-exporter
          command:
            - /tenant-quota-exporter
          env:
            - name: signalfxToken
              valueFrom:
                secretKeyRef:
                  name: tenant-quota-exporter-secret
                  key: sfxToken
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
          imagePullPolicy: Always
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: tenant-quota-exporter-env
          image: tenant-quota-exporter
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      serviceAccountName: paas-metrics-collector
      serviceAccount: paas-metrics-collector
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
