---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: signalfx-allocated-resource-metrics
  newName: images.paas.redhat.com/itpaas-util-images/signalfx-allocated-resource-metrics-collector
  newTag: v1.0.1

resources:
- allocated-resources-collector-deployment.yaml
