---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: paas-reporter-cluster-reader
subjects:
  - kind: ServiceAccount
    name: paas-reports
    namespace: paas-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: paas-reporter-cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: paas-reports
    namespace: paas-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view