apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: splunk-otel-collector-role
  namespace: paas-otel
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update
      - watch
      - list
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update

